#HikariCp ì„¤ì •
spring:
  datasource:
    password: dowon
    username: dowon
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test

bot:
  token: 1132709981:AAEVzFP079An7ica_ZM7Cg5JKm3T88-oa1I
  username: plovelyBot

word:
  search: ê²€ìƒ‰ìœ¼ë¡œ ì¶”ê°€ ğŸ˜Š
  addr: ì£¼ì†Œë¡œ ì¶”ê°€ ğŸ 
  alarm: ì•Œë¦¼ë“±ë¡ â­•
  alarmDel: ì•Œë¦¼ì‚­ì œ âŒ
  home: ì²˜ìŒìœ¼ë¡œ ëŒì•„ê°€ê¸° ğŸ› 



